### ISSUE TITLE
`RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by AlttiRi** [nE0sIghT/ascii85.js#1]
It fails on long strings.

Just use
```js
return output.reduce((accumulator, byte) => accumulator + String.fromCharCode(byte), "");
```
instead of this

https://github.com/nE0sIghT/ascii85.js/blob/84a8eb5792eacd8bc7f0cda68bb9c0d23b40ce70/ascii85.js#L114

---

Also, format the code, please. 
_At least_, replace tabs with spaces. 

`Ctrl+Alt+L` if you use WebStorm/IDEA, also take a look at the IDE warnings (`==`, `!=`, `var`, `Exception`).

**Comment by nE0sIghT** [comment]
Hello.

You can use Github's [Pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) to provide proper patch.
