### ISSUE TITLE
Don't use `TextDecoder`/`TextEncoder`

### ISSUE THREAD

**Issue by AlttiRi** [nE0sIghT/ascii85.js#2]
Never use `TextDecoder`/`TextEncoder` with [binary strings](https://web.archive.org/web/20220316230750/https://developer.mozilla.org/en-US/docs/Web/API/DOMString/Binary) ([ByteString](https://web.archive.org/web/20210608032047/https://developer.mozilla.org/en-US/docs/Web/API/ByteString)).

Replace the appropriate code with the follow:
https://github.com/AlttiRi/meganz-api/blob/33c35620162a653bb1a14ada6cd13979e9ad58f9/src/util.js#L34-L83

See the comments in JSDoc.

---

Just try to encode images, then try to decode them back.

**Comment by nE0sIghT** [comment]
Hello.

You can use Github's [Pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) to provide proper patch.
